# Spring Application Name
spring.application.name=taskmaster-backend

# Spring DataSource Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/taskmaster_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA Configuration
spring.jpa.database: postgresql
spring.jpa.show-sql: true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto: update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=pe.edu.upc.taskmaster.backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7

# Habilitar endpoints de metricas
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6Iz_b74PUSv1n37uDcmKII5swZWrixAR5T-2QPT1WeOZA}
gemini.api.model=gemini-3.1-flash-lite
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.api.timeout=60000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/calendar.events

spring.security.oauth2.client.registration.google.redirect-uri=https://backend-taskmaster-1.onrender.com/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Frontend origin used by the OAuth callback page
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
